# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('web', '0001_initial'), ('web', '0002_auto_20160622_0001'), ('web', '0003_auto_20160622_0113'), ('web', '0004_auto_20160622_0114'), ('web', '0005_team_total_score'), ('web', '0006_team_total_score')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('score_1', models.FloatField(default=0.0)),
                ('member_1', models.CharField(max_length=100)),
                ('member_2', models.CharField(blank=True, max_length=100)),
                ('member_3', models.CharField(blank=True, max_length=100)),
                ('member_4', models.CharField(blank=True, max_length=100)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254)),
                ('email_3', models.EmailField(blank=True, max_length=254)),
                ('email_4', models.EmailField(blank=True, max_length=254)),
                ('size_1', models.CharField(blank=True, choices=[('', 'None'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=1, null=True)),
                ('size_2', models.CharField(blank=True, choices=[('', 'None'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=1, null=True)),
                ('size_3', models.CharField(blank=True, choices=[('', 'None'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=1, null=True)),
                ('size_4', models.CharField(blank=True, choices=[('', 'None'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='', max_length=1, null=True)),
                ('diet', models.CharField(blank=True, max_length=1000)),
                ('code', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('last_login', models.DateTimeField(null=True)),
                ('score_10', models.FloatField(default=0.0)),
                ('score_2', models.FloatField(default=0.0)),
                ('score_3', models.FloatField(default=0.0)),
                ('score_4', models.FloatField(default=0.0)),
                ('score_5', models.FloatField(default=0.0)),
                ('score_6', models.FloatField(default=0.0)),
                ('score_7', models.FloatField(default=0.0)),
                ('score_8', models.FloatField(default=0.0)),
                ('score_9', models.FloatField(default=0.0)),
                ('total_score', models.FloatField(default=0.0)),
            ],
        ),
    ]
