# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='score',
            new_name='score_1',
        ),
        migrations.AddField(
            model_name='team',
            name='score_10',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='score_2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='score_3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='score_4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='score_5',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='score_6',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='score_7',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='score_8',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='score_9',
            field=models.FloatField(default=0.0),
        ),
    ]
