# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160622_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='score_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score_9',
            field=models.IntegerField(default=0),
        ),
    ]
