# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160622_0114'),
    ]
